version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
  mongo:
    image: mongo:4.4
  perf:
    image: pivotalrabbitmq/perf-test:latest
    depends_on:
      - rabbitmq
    command: "--uri amqp://rabbitmq -k test.enrichwithbibleverse --exchange test -t topic -jb -r 10 -z 300 -y 0"
  app:
    build: .
    environment:
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - 9000:9000
